### ISSUE TITLE
work out why rocksdb doesn't like being cached

### ISSUE THREAD

**Issue by alsuren** [cargo-quick/kache#4]

**Comment by alecmocatta** [comment]
My current best guess is this is due to [`tokio_tar::Entry::unpack_in`](https://docs.rs/tokio-tar/0.3/tokio_tar/struct.Entry.html#method.unpack_in) touching the `mtime` of a directory when it unpacks a file inside that directory? See https://github.com/alexcrichton/tar-rs/pull/217. Mildly surprising that cargo's `rerun-if-changed` would trigger on a directory `mtime` changing.
